title: Budak Lembur
description: Tempat menyimpan hasil googling, mungkin lain kali bisa berguna kembali.

url: http://irfansyh.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: irfansyh
  twitter: brianmaierjr
  facebook: presiden.irfans
  email: irfans.putra15@gmail.com
  linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: budaklembur
